### ISSUE TITLE
contact.html을 mailer.php와 연동하여 보내기

### ISSUE THREAD

**Issue by vlaksuga** [vlaksuga/kawasaki#1]
@brilliaflo 
![image](https://user-images.githubusercontent.com/45654321/57290597-b6a55680-70f8-11e9-8a5e-0909f69dbf7c.png)

[http://vlaksuga.github.io/kawasaki/contact.html](url)
[http://vlaksuga.github.io/kawasaki/mailer.php](url)를 연동하는 문제입니다.

현재 상태는 405 오류가 뜹니다

**Comment by brilliaflo** [comment]
php는 깃헙에서 돌아가지 않습니다.

**Comment by brilliaflo** [comment]
@vlaksuga 이거 처리해주삼

**Comment by vlaksuga** [comment]
알겠습니다.

**Comment by vlaksuga** [comment]
도커 깔고 코드이그나이터로
블랙슈가용 php 프레임워크 만들어주시면 좋겠습니다.

**Comment by brilliaflo** [comment]
@vlaksuga 이걸 굳이 코드이그나이터로 할것은 아닌데.
 
오해가있으신가봅니다

**Comment by vlaksuga** [comment]
@brilliaflo 
업체에서 굳이 메일로 보내기 안할것 같습니다.
오픈채팅으로 연결한다고 하네요. 그래서 이 이슈는 현재기준으로 해결 안해도 되는 이슈입니다.

**Comment by brilliaflo** [comment]
@vlaksuga 예 그럼 클로즈 해주세요.
근데 오픈채팅이 머지요?
